/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiJarvisTtsRouteImport } from './routes/api/jarvis.tts'
import { Route as ApiJarvisSttRouteImport } from './routes/api/jarvis.stt'
import { Route as ApiJarvisN8nRouteImport } from './routes/api/jarvis.n8n'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJarvisTtsRoute = ApiJarvisTtsRouteImport.update({
  id: '/api/jarvis/tts',
  path: '/api/jarvis/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJarvisSttRoute = ApiJarvisSttRouteImport.update({
  id: '/api/jarvis/stt',
  path: '/api/jarvis/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJarvisN8nRoute = ApiJarvisN8nRouteImport.update({
  id: '/api/jarvis/n8n',
  path: '/api/jarvis/n8n',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/jarvis/n8n': typeof ApiJarvisN8nRoute
  '/api/jarvis/stt': typeof ApiJarvisSttRoute
  '/api/jarvis/tts': typeof ApiJarvisTtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/jarvis/n8n': typeof ApiJarvisN8nRoute
  '/api/jarvis/stt': typeof ApiJarvisSttRoute
  '/api/jarvis/tts': typeof ApiJarvisTtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/jarvis/n8n': typeof ApiJarvisN8nRoute
  '/api/jarvis/stt': typeof ApiJarvisSttRoute
  '/api/jarvis/tts': typeof ApiJarvisTtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/jarvis/n8n' | '/api/jarvis/stt' | '/api/jarvis/tts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/jarvis/n8n' | '/api/jarvis/stt' | '/api/jarvis/tts'
  id:
    | '__root__'
    | '/'
    | '/api/jarvis/n8n'
    | '/api/jarvis/stt'
    | '/api/jarvis/tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiJarvisN8nRoute: typeof ApiJarvisN8nRoute
  ApiJarvisSttRoute: typeof ApiJarvisSttRoute
  ApiJarvisTtsRoute: typeof ApiJarvisTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jarvis/tts': {
      id: '/api/jarvis/tts'
      path: '/api/jarvis/tts'
      fullPath: '/api/jarvis/tts'
      preLoaderRoute: typeof ApiJarvisTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jarvis/stt': {
      id: '/api/jarvis/stt'
      path: '/api/jarvis/stt'
      fullPath: '/api/jarvis/stt'
      preLoaderRoute: typeof ApiJarvisSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jarvis/n8n': {
      id: '/api/jarvis/n8n'
      path: '/api/jarvis/n8n'
      fullPath: '/api/jarvis/n8n'
      preLoaderRoute: typeof ApiJarvisN8nRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiJarvisN8nRoute: ApiJarvisN8nRoute,
  ApiJarvisSttRoute: ApiJarvisSttRoute,
  ApiJarvisTtsRoute: ApiJarvisTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
